//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiskView.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFZSURBVDhPjZNbcoJAEEVdUnaYxAfxgdEIimjEYNQd4SL88Su8Bqszd5iRR+cjU3WLH85puqfpmHM6nej7eKTD4UBhGNJ+/0VBENDnbkfb7Zb8zQbPm+u6TxppHsD3+/2RAimqnM9nulwutPb9vyWoDDAXgvJcUJbnlGU5pToQXK9XiqKIPM+7aaw6+GwlMHBDkCmBbdsq88WCNFYd9AwBh0tBmmaUyAhR0Gz+wQUYGPrmsIyGjWA6m3EBpo1hMVhWN3CSpkpgT9+5AFcFQRuuqqcUJ6VgYk+5APdcCiTUAHUkbASj8YQL1mtfCgoOysoGLgWChqMxF6w8j4QUtGEDqsSJ2hNrOOSC5WpVCuSL9YomPxJGIBhYb1zguEvVXxuMkxKsC3oDiwsWjtMU1KC2oNvvcwHWU/0H/8hLt8cFWE9sGJYE94yrwrQxMPSMz0ZlwM+vXS3odH4ByCWlQa2uev8AAAAASUVORK5CYII=")]
        public string DefaultFileDataUri {
            get {
                return ((string)(this["DefaultFileDataUri"]));
            }
        }
    }
}
